# Generated by Django 4.2.16 on 2026-05-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound')], default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email Only'), ('telegram', 'Telegram Only'), ('both', 'Email + Telegram'), ('browser', 'Browser Only')], default='email', max_length=10),
        ),
    ]
