# Generated by Django 4.2.16 on 2026-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email Only'), ('telegram', 'Telegram Only'), ('email_telegram', 'Email + Telegram')], default='email', max_length=20),
        ),
    ]
