# Generated by Django 4.2.16 on 2026-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldSilverRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=10)),
                ('price_inr', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=4, max_digits=12)),
                ('daily_high', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('daily_low', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('percentage_change', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('usd_inr_rate', models.DecimalField(decimal_places=4, default=83.5, max_digits=8)),
                ('raw_price_oz_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gold/Silver Rate',
                'verbose_name_plural': 'Gold/Silver Rates',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metal', 'timestamp'], name='rates_golds_metal_b023c0_idx')],
            },
        ),
    ]
