# Generated by Django 4.2.16 on 2026-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
