# Generated by Django 4.2.16 on 2026-05-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationhistory_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('browser', 'Browser'), ('telegram', 'Telegram')], max_length=10),
        ),
    ]
